pkg/web/html/overtimereport_view.go, pkg/web/html/overtimereport_view_test.go
* Instead of formatting overtime hours as "1h30m" or "1.5h" it displays "1:30"
=> Better formatted overtime hours

.github/workflows/deploy.yaml, README.md, envs/helmfile.yaml, envs/preview.yaml, envs/prod.yaml
* Adds GH workflow that automatically runs `helmfile apply` for `v1.2.3` tags and preseleases `v1.2.3-rc1`
=> Automatically deploy releases and prereleases

pkg/web/attendance_handlers.go
If someone entered a username in "for someone else", it would still display their own attendance, but change the name in the title to the other. This is confusing.
=> Fix wrong session ID

pkg/web/session_handlers.go, test/session_test.go
The redirect caused the browser to be redirected to '/', but they were issueing POST requests instead of GET.
=> Fix redirect after login

pkg/odoo/employee.go, pkg/web/attendance_handlers.go
The field returned by the employee query didn't have the desired effect.
So we'll just try to fetch them anyway.
It's a step backwards in UX but I couldn't quickly figure how to check permissions.
=> Remove check for attendance access for other users

pkg/odoo/contract.go, pkg/timesheet/dailysummary.go, pkg/timesheet/dailysummary_test.go, pkg/timesheet/report.go, pkg/timesheet/report_test.go, pkg/web/report_handler.go
The times from Odoo are returned in UTC.
However, there are cases where some overtime hours are moved to the next date between 00:00 and 01:00 (resp. 02:00 in summer).
This change should fix the calculation to Europe/Zurich timezone
=> Localize time zones when calculating overtime

Dockerfile, Makefile, chart/templates/deployment.yaml, envs/preview.yaml
* Adds Make targets to deploy to `odootools-preview`, at least from a local workstation
* Adds tzdata to Docker image. Without it, Timezones fail silently
=> Fix timezone in Deployment

.github/PULL_REQUEST_TEMPLATE.md, pkg/timesheet/report.go, pkg/web/views/overtimereport_view.go, templates/overtimereport.html
* Adds "Previous", "Current" and "Next" links to the top, allowing navigating between months.
* Closes #22 
=> Add navigational links to switch between months

pkg/odoo/employee.go
Without the filtering the fields, all fields are returned.
But some fields returned are behind access control and then all fields get denied
This change reverts commenting out something that was part of #33 while testing
=> Fix access error when trying to retrieve Employee

pkg/odoo/attendance.go, pkg/odoo/date.go, pkg/odoo/leave.go, pkg/timesheet/report.go, pkg/web/report_handler.go
* Fixes an issue where not attendances from previous month are missing due to different timezones.
* Fixes calculation where an attendances has the same timestamp as the first second of the same day.
=> Fix calculation around attendances after starting a new month

.github/workflows/deploy-preview.yaml, .github/workflows/destroy-preview.yaml
* Ignores preview deployments when PRs have the `dependency` label. This will avoid open Renovate PRs to consume unnecessary resources, especially over long time.
* follow-up of #37 
=> Don't run preview deployments when updating dependencies

pkg/odoo/payslip.go, pkg/odoo/payslip_test.go, pkg/web/overtimereport/overtimereport_controller.go, pkg/web/overtimereport/overtimereport_request.go, pkg/web/overtimereport/overtimereport_view.go, templates/overtimereport.html
* Closes #26 
* The overtime report now adds the overtime delta with the overtime information that is stored in the last payslip to display the new balance.
NOTE: The "overtime" field is a custom field added to Payslips. This isn't the case since the beginning, so very old overtime reports will not show the balance if that field is missing.
=> Display new overtime balance in overtime report

pkg/timesheet/dailysummary.go, pkg/timesheet/dailysummary_test.go, pkg/timesheet/report.go, pkg/timesheet/report_test.go, pkg/timesheet/yearly_report.go, pkg/web/overtimereport/monthlyreport_view.go, pkg/web/overtimereport/yearlyreport_view.go
* The exact leave duration is needed to calculate overtime, however for displaying leaves it was not human friendly and sometimes actually wrong.
* Now, the reports show "full days" since in Odoo, we can only register full leave days, not partial days.
=> Fix holiday summary

pkg/timesheet/yearly_report.go, pkg/timesheet/yearly_report_test.go
* For people that started in the middle of the current year the months are hidden and not calculated in the yearly report view
=> Don't display months in yearly reports where contract didn't start

pkg/timesheet/dailysummary.go, pkg/timesheet/dailysummary_test.go
* The total counter will now ignore public holidays
=> Don't count public holidays in the total

pkg/web/overtimereport/yearlyreport_view.go
* When browsing through yearly reports, it was only visible in the URL which year someone is looking at. This PR adds the year to the direct links for better UX
=> Add year digits to monthly report links

Makefile
The current make target only loaded `main.go` while some methods are in
other go files.
=> Ensure `make run` can actually run odootools

templates/overtimereport-yearly.html
This was not immediately obvious to me so I thought it won't hurt to make it obvious.
Brings the report in line with the monthly report.
=> Tell units when it's not hours in yearly report

pkg/timesheet/report.go, pkg/timesheet/report_test.go, pkg/timesheet/yearly_report.go, pkg/web/overtimereport/overtimereport_controller.go
Previously it was only visible in the logs and the report showed empty values.
This is bad UX since it's not very transparent why it's empty.
=> Abort reporting with error when contracts cannot be accessed

pkg/web/overtimereport/overtimereport_controller.go, pkg/web/reportconfig/config_request.go
When calculating the date ranges to use for fetching data from Odoo,
take into account yearly reports. The current implementation only ever
fetches data in January.
Fixes: #70
=> Fix date range calculations of yearly report

pkg/timesheet/dailysummary.go, pkg/timesheet/dailysummary_test.go, pkg/timesheet/report.go, pkg/web/controller/view.go, pkg/web/employeereport/employeereport_view.go, pkg/web/overtimereport/monthlyreport_view.go, pkg/web/reportconfig/config_view.go, templates/employeereport.html, templates/layout.html
* Internal refactoring how overtime is calculated. The changes allow to access individual sums of certain types of hours per work day.
* Thanks to the refactoring, a new column `ouf of office, real` is displayed in the employee report, next to `worked hours`. This column shows specifically the share of out-of-office hours (without 1.5 multiplication) that ultimately make up `worked hours`.
* Since the employee report is only accessible for HR managers, this column is exclusive to HR managers in Odoo.
* Closes #91 
* As a side change, the max width of the employee report has been increased on large screens (> 2000px) to better fit the larger table.
=> Add Out-of-office hours column to employee report

pkg/odoo/model/contract.go, pkg/web/employeereport/employeereport_controller.go, pkg/web/employeereport/employeereport_controller_test.go
* Adds a custom error implementation for "contract found"
* Fixes the following panic:
```
..."method":"POST","uri":"/report"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x84903e]
goroutine 199 [running]:
github.com/vshn/odootools/pkg/web/employeereport.(*EmployeeReport).ignoreNoContractFound(0xc0003e7cc0?, {0x84cc19?, 0xc00029a480?}, {0x0, 0x0})
/home/runner/work/odootools/odootools/pkg/web/employeereport/employeereport_controller.go:191 +0x1e
```
=> Fix nil pointer panic in error handling for employee report

pkg/odoo/model/payslip.go, pkg/web/overtimereport/monthlyreport_view.go, pkg/web/overtimereport/overtimereport_controller.go, templates/help.html, templates/overtimereport-monthly.html
* This PR introduces more details like total excused and worked hours.
* "new balance" is renamed into "calculated balance".
* New field "definitive balance" now shows the balance that is in the current month's payslip, if any.
* Title now also shows which month and year you're looking at
This is because sometimes there are discrepancies  between calculated and actual overtime made with manual correction from peopleops.
Fixes #128 
=> Rework monthly report summary

pkg/odoo/model/actionreason.go, pkg/odoo/model/attendance.go, pkg/timesheet/report.go, pkg/timesheet/report_test.go, pkg/web/overtimereport/overtimereport_controller.go, pkg/web/reportconfig/config_controller.go
This change includes the current time and adds a "fake sign_out" so that the overtime calculation of  "today" is respecting a currently-signed-in shift.
The result is that a "current month" report now also includes the worked hours since last sign in and doesn't show an incorrect overtime. For example, for an 8h day, if a user worked for 7h already, the monthly report shows only a 1h instead of 8h undertime for "today".
=> Include current time in monthly report as sign_in

CONTRIBUTING.md, flags.go, pkg/odoo/model/attendance.go, pkg/odoo/model/payslip.go, pkg/odoo/model/payslip_test.go, pkg/odoo/model/user.go, pkg/odoo/timezone.go, pkg/odoo/timezone_test.go, pkg/timesheet/report.go, pkg/timesheet/report_test.go, pkg/web/controller/controller.go, pkg/web/employeereport/employeereport_controller.go, pkg/web/employeereport/employeereport_view.go, pkg/web/employeereport/employeereport_view_test.go, pkg/web/employeereport/update_payslip_controller.go, pkg/web/overtimereport/monthlyreport_view.go, pkg/web/overtimereport/overtimereport_controller.go, pkg/web/reportconfig/config_controller.go, templates/help.html, templates/overtimereport-monthly.html, web_command.go
With this change, the weekly and monthly report now calculate and show the times in the timezone of the employee.
The timezone information can come from different sources, according to preference:
- From the payslip (added by PeopleOps)
- From the user preferences (only for own report in the current month)
- Default of Europe/Zurich (changeable by CLI flag)
The yearly report will be updated in a later PR.
See also #120 
=> Introduce support for different time zones in monthly report

pkg/odoo/timezone.go, pkg/odoo/timezone_test.go
Without MarshalJSON for TimeZone, then the field gets serialized as "{}", which Odoo accepts and then  also returns this when querying again, causing UnmarshalJSON of the TimeZone to fail again.
=> Fix saving timezone when updating a payslip

pkg/odoo/date.go, pkg/odoo/date_test.go
Fixes an issue where a new value of overtime in payslip cannot be saved.
=> Fix payslip saves

pkg/odoo/date.go, pkg/odoo/model/leave.go, pkg/odoo/model/leave_test.go, pkg/timesheet/dailysummary.go, pkg/timesheet/dailysummary_test.go, pkg/timesheet/report.go, pkg/timesheet/report_test.go, pkg/timesheet/yearly_report.go, pkg/web/overtimereport/monthlyreport_controller.go
* Leaves didn't correctly respect timezones.
* Reported excused time could actually exceed the daily max time, now they are capped.
=> Fix leaves and excused times in monthly report

pkg/odoo/model/attendance.go, pkg/odoo/model/attendance_test.go, pkg/timesheet/dailysummary.go, pkg/timesheet/dailysummary_test.go, pkg/timesheet/report.go, pkg/timesheet/report_test.go, pkg/timesheet/validationerror.go, pkg/timesheet/yearly_report.go, pkg/web/controller/view.go, pkg/web/employeereport/employeereport_view.go, pkg/web/overtimereport/monthlyreport_view.go, pkg/web/overtimereport/yearlyreport_view.go, pkg/web/reportconfig/config_controller.go, templates/employeereport.html, templates/overtimereport-monthly.html, templates/overtimereport-yearly.html
This feature will display errors when attendances are recorded wrongly. In the monthly report, a validation error will be displayed with a warning sign and the error message. In the yearly report, a warning icon is displayed next to the month's link if the month contains at least one violation.
In the employee report, the same icon is displayed in the row of the affected employee.
This PR changes how attendances are grouped into shifts. This also causes a few reports where overtime is calculated wrongly since it ignores invalid shifts.
Documentation is in a follow-up PR
=> Timesheet Validation

pkg/timesheet/report.go, pkg/timesheet/report_test.go
Fixes an issue that if there are 2 consecutive sign_ins, the first sign_in would be ignored.
Now it can properly detect a validation error with double sign_in's.
=> Fix bug that would ignore double sign_in in shifts

pkg/web/reportconfig/config_controller.go
Fixes an issue where leaves would not show up in the weekly report, but only in monthly or yearly report.
This is due to timezone issue (again...)
=> Fix timezone in weekly report

pkg/timesheet/report.go
Fixes an issue where a leave spanning a weekend would not be recognized on a Monday if in different timezone
=> Fix leave calculation if leave was on Monday in vancouver

pkg/web/reportconfig/config_request.go, templates/createreport.html
The radio check is unnecessary. 
We can just check if the username input has a value.
This cleans up the `/report` view a bit.
=> Remove radio check for HR manager

templates/layout.html
On very large screens the table gets widened to a point where it's becoming less readable.
This PR limits the max width of the main container.
=> Limit the max width for very wide screens
