vshn/odootools

- cmd/web.go
- doc/design.md
- main.go
- pkg/odoo/attendance.go
- pkg/odoo/client.go
- pkg/odoo/date.go
- pkg/odoo/date_test.go
- pkg/odoo/leave.go
- pkg/odoo/leave_test.go
- pkg/timesheet/dailysummary.go
- pkg/timesheet/dailysummary_test.go
- pkg/timesheet/report.go
- pkg/timesheet/report_test.go
- pkg/web/attendance_handlers.go
- pkg/web/html/overtimereport_view.go
- templates/overtimereport.html
* Add business rules that considers leaves (except "Unpaid" leave)
* Add new column to attendance report
> Consider Leaves in calculating overtime

- chart/.helmignore
- chart/Chart.yaml
- chart/templates/NOTES.txt
- chart/templates/_helpers.tpl
- chart/templates/deployment.yaml
- chart/templates/ingress.yaml
- chart/templates/route.yaml
- chart/templates/secret.yaml
- chart/templates/service.yaml
- chart/templates/serviceaccount.yaml
- chart/values.yaml
- envs/helmfile.yaml
- envs/prod.yaml
* Adds a local helm chart
* Adds Helmfile support for declarative config
* Prepares for automated deployment
> Add Helm chart

- pkg/odoo/attendance.go
- pkg/odoo/employee.go
- pkg/odoo/leave.go
- pkg/timesheet/report.go
- pkg/web/attendance_handlers.go
- pkg/web/html/overtimereport_view.go
- pkg/web/html/requestreport_view.go
- pkg/web/session_handlers.go
- templates/createreport.html
- templates/overtimereport.html
- test/session_test.go
Provided user has access to other employees, one can generate a report for that user.
Especially useful for people in HR.
> Add support to create report for someone else

- pkg/odoo/actionreason.go
- pkg/odoo/attendance.go
- pkg/odoo/date.go
- pkg/odoo/employee.go
- pkg/odoo/leave.go
- pkg/odoo/leavetype.go
- pkg/odoo/model.go
- pkg/web/attendance_handlers.go
* Should improve performance by only selectively searching for results in the desired month (instead of fetching all)
> Optimize leave and attendance queries

- pkg/web/attendance_handlers.go
- pkg/web/server.go
- pkg/web/session_handlers.go
- pkg/web/views/overtimereport_view.go
- pkg/web/views/overtimereport_view_test.go
- pkg/web/views/renderer.go
- pkg/web/views/requestreport_view.go
Hopefully Odoo does already the escape, but we'll do it here as well, just to be sure.
> Escape username

- pkg/odoo/employee.go
- pkg/web/report_handler.go
- pkg/web/routes.go
- pkg/web/views/error_view.go
- pkg/web/views/overtimereport_view.go
- templates/error.html
- templates/nav.html
* This better prepares for new features that aren't POST based
* Create dedicated Error view
> Get Report parameters from URL path instead of form fields

- templates/layout.html
Less external dependencies and tracking
Not that the font really matters in this tool, any default looks good enough
> Remove google fonts

- .github/workflows/deploy-preview.yaml
- .github/workflows/destroy-preview.yaml
- Makefile
- README.md
- envs/helmfile.yaml
- envs/test.yaml
* This PR adds a pipeline that deploys a preview instance with each PR with the `pr-#nr` suffix in the Test namespace
* When closing the PR (close or merge) then the instance gets removed.
* A comment in the PR is added when the deployment is rolled out or teared down.
> Add Preview pipeline

- .github/workflows/deploy-master.yaml
- .github/workflows/deploy-prod.yaml
This change allows to update Helm template and values to production without having to push a new Git tag
Related to #37 
> Add deployment pipeline in master branch

- .github/workflows/deploy-master.yaml
- .github/workflows/deploy-preview.yaml
- .github/workflows/deploy-prod.yaml
- Makefile
- envs/helmfile.yaml
In all environments, Odoo is now behind oauth, thus we directly can connect via internal service
> Set static odoo URL

- go.mod
- go.sum
- pkg/web/common_context.go
- pkg/web/report_handler.go
- pkg/web/server.go
- test/integration_test.go
Pipelines better convey the big picture of a process to handle the request.
Also, they focus on business logic, rather than error handling.
> Refactor: Introduce pipelines for request handlers

- .github/workflows/deploy-master.yaml
- .github/workflows/deploy-preview.yaml
- .github/workflows/deploy-prod.yaml
* Uses GitHub Environments to select environment-specific secrets
> Update workflows to use GitHub environments

- pkg/web/routes.go
- pkg/web/server.go
- renovate.json
- templates/help.html
- templates/nav.html
> Add help page

- Makefile
- Makefile.vars.mk
`Make` targets fall back to `podman`
> Development: Support running/building with Podman

- pkg/odoo/date.go
- pkg/odoo/model/attendance.go
- pkg/odoo/model/attendance_test.go
- pkg/odoo/model/contract.go
- pkg/odoo/model/odoo_test.go
- pkg/timesheet/report.go
- pkg/timesheet/report_test.go
- pkg/timesheet/yearly_report.go
- pkg/timesheet/yearly_report_test.go
- pkg/web/controller/view.go
- pkg/web/employeereport/employeereport_controller.go
- pkg/web/employeereport/employeereport_view.go
- pkg/web/overtimereport/monthlyreport_view.go
- pkg/web/overtimereport/overtimereport_controller.go
- pkg/web/overtimereport/yearlyreport_view.go
- pkg/web/report_handler.go
- pkg/web/reportconfig/config_controller.go
- pkg/web/reportconfig/config_controller_test.go
- pkg/web/reportconfig/config_request.go
- pkg/web/reportconfig/config_view.go
- templates/createreport.html
Adds the current week's attendance to the /report landing page.
Closes #82 
> Add a weekly report to the config view

- pkg/web/reportconfig/config_controller.go
- pkg/web/reportconfig/config_view.go
- templates/createreport.html
> Display a warning if weekly report can't be generated

- .github/workflows/lint.yaml
- .github/workflows/test.yaml
- flags.go
- main.go
- pkg/odoo/client_test.go
- pkg/odoo/debug.go
- pkg/odoo/model/odoo_test.go
- pkg/odoo/model/payslip.go
- pkg/odoo/model/workingschedule.go
- pkg/odoo/session_test.go
- pkg/web/employeereport/employeereport_controller_test.go
- pkg/web/overtimereport/overtimereport_controller.go
- pkg/web/session_handlers_test.go
- test/integration_test.go
- test/static_test.go
- web_command.go
* Replace codeclimate with golang-ci
* Resolve linting issues detected by golang-ci
* Replace deprecated function calls
* Move CLI flags into dedicated file
> Update CI and other boilerplate

- pkg/web/employeereport/employeereport_controller.go
> Fix crash when generating an employee report

- main.go
- pkg/web/cookie.go
- pkg/web/routes.go
- pkg/web/server.go
- pkg/web/server_test.go
- pkg/web/version.go
- templates/about.html
- templates/nav.html
- test/integration_test.go
- web_command.go
Adds a page that contains the Odootools version and release notes link.
> Add "About" page to display version and release notes

- templates/createreport.html
- templates/overtimereport-monthly.html
- templates/overtimereport-yearly.html
> Aligned hours column to the right and change font to monospace

- pkg/web/controller/view.go
- pkg/web/controller/view_test.go
- pkg/web/overtimereport/monthlyreport_view.go
- pkg/web/overtimereport/yearlyreport_view.go
- templates/createreport.html
- templates/help.html
- templates/overtimereport-monthly.html
- templates/overtimereport-yearly.html
> Change Overtime & Undertime color

- templates/createreport.html
- templates/overtimereport-monthly.html
- templates/overtimereport-yearly.html
> Change fontsize to bold

- templates/nav.html
Adds more horizontal gap to the navbar items to make them more readable.
> Space out items on navbar
